### PR TITLE
Fix TypeError on empty translate key

### LINKED ISSUE #51: Publishing doesn't work anymore with default schema
Probably also related to https://github.com/dini-ag-kim/lrmi-profile/pull/16. Clicking on publish at https://skohub.io/editor/ results in the screen being blank and the web form being empty after clicking on the back button of the browser.

### PR DESCRIPTION
**Pull request by literarymachine**
Fixes #51, or rather the underlying bug.

### CODE REVIEW

**Review by fsteeg — APPROVED** [review]
Looks good to me, the form does not go to the blank page, but validates instead, staying on the form page.

**Comment by dr0i** [comment]
Hm, I cannot reproduce the problem, i.e. when I click on 'publish' just nothing happens (besides the first two mandatory fields turning red (validation process?)). Deploying this PR doesn't change anything. I probably miss something.

**Comment by acka47** [comment]
@dr0i This is probably because the default schema has been updated in the meantime see https://github.com/dini-ag-kim/lrmi-profile/commit/6452adb5704962e7fbf0ccc8ab0e03944555a3ff. For testing this you should use this schema: https://raw.githubusercontent.com/dini-ag-kim/lrmi-profile/7aae393f58ebfa4a1e7c3c8f87ecc041f2a9747b/draft/schemas/schema.json

**Comment by dr0i** [comment]
@acka47 ah - thx this did the trick :)
Getting no more blank side but now I get an `Error.oneOf` a the top of the side after clicking `publish`.

**Review by dr0i — APPROVED** [review]

**Comment by dr0i** [comment]
Deployd to test and production, closed.

**Pull request merged**
